package fr.utbm.core.entity;// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Alerthis generated by hbm2java
 */
public class Alerthis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 272092179767751953L;
	private int alhId;
	private Trigger trigger;
	private Date alhDate;
	private boolean alhState;

	public Alerthis() {
	}

	public Alerthis(int alhId, Trigger trigger, Date alhDate, boolean alhState) {
		this.alhId = alhId;
		this.trigger = trigger;
		this.alhDate = alhDate;
		this.alhState = alhState;
	}

	public int getAlhId() {
		return this.alhId;
	}

	public void setAlhId(int alhId) {
		this.alhId = alhId;
	}

	public Trigger getTrigger() {
		return this.trigger;
	}

	public void setTrigger(Trigger trigger) {
		this.trigger = trigger;
	}

	public Date getAlhDate() {
		return this.alhDate;
	}

	public void setAlhDate(Date alhDate) {
		this.alhDate = alhDate;
	}

	public boolean isAlhState() {
		return this.alhState;
	}

	public void setAlhState(boolean alhState) {
		this.alhState = alhState;
	}

}
