package fr.utbm.core.entity;

// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Alert generated by hbm2java
 */
public class Alert implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8528049633595361584L;
	private String alrCode;
	private String alrLabel;
	private String alrDescription;
	private Set<Trigger> triggers = new HashSet<Trigger>(0);

	public Alert() {
	}

	public Alert(String alrCode, String alrLabel, String alrDescription) {
		this.alrCode = alrCode;
		this.alrLabel = alrLabel;
		this.alrDescription = alrDescription;
	}

	public Alert(String alrCode, String alrLabel, String alrDescription,
			Set<Trigger> triggers) {
		this.alrCode = alrCode;
		this.alrLabel = alrLabel;
		this.alrDescription = alrDescription;
		this.triggers = triggers;
	}

	public String getAlrCode() {
		return this.alrCode;
	}

	public void setAlrCode(String alrCode) {
		this.alrCode = alrCode;
	}

	public String getAlrLabel() {
		return this.alrLabel;
	}

	public void setAlrLabel(String alrLabel) {
		this.alrLabel = alrLabel;
	}

	public String getAlrDescription() {
		return this.alrDescription;
	}

	public void setAlrDescription(String alrDescription) {
		this.alrDescription = alrDescription;
	}

	public Set<Trigger> getTriggers() {
		return this.triggers;
	}

	public void setTriggers(Set<Trigger> triggers) {
		this.triggers = triggers;
	}

}
