package fr.utbm.core.entity;// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Sensor generated by hbm2java
 */
public class Sensor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9188007067032976059L;
	private int senId;
	private Station station;
	private String senLabel;
	private Set<Trigger> triggers = new HashSet<Trigger>(0);
	private Set<Temperature> temperatures = new HashSet<Temperature>(0);

	public Sensor() {
	}

	public Sensor(int senId, Station station, String senLabel) {
		this.senId = senId;
		this.station = station;
		this.senLabel = senLabel;
	}

	public Sensor(int senId, Station station, String senLabel,
			Set<Trigger> triggers, Set<Temperature> temperatures) {
		this.senId = senId;
		this.station = station;
		this.senLabel = senLabel;
		this.triggers = triggers;
		this.temperatures = temperatures;
	}

	public int getSenId() {
		return this.senId;
	}

	public void setSenId(int senId) {
		this.senId = senId;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	public String getSenLabel() {
		return this.senLabel;
	}

	public void setSenLabel(String senLabel) {
		this.senLabel = senLabel;
	}

	public Set<Trigger> getTriggers() {
		return this.triggers;
	}

	public void setTriggers(Set<Trigger> triggers) {
		this.triggers = triggers;
	}

	public Set<Temperature> getTemperatures() {
		return this.temperatures;
	}

	public void setTemperatures(Set<Temperature> temperatures) {
		this.temperatures = temperatures;
	}

}
