package fr.utbm.core.entity;// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 147312721720773657L;
	private int staId;
	private Area area;
	private String staLabel;
	private Date staLastCom;
	private boolean staValid;
	private Set<Sensor> sensors = new HashSet<Sensor>(0);

	public Station() {
	}

	public Station(int staId, Area area, String staLabel, boolean staValid) {
		this.staId = staId;
		this.area = area;
		this.staLabel = staLabel;
		this.staValid = staValid;
	}

	public Station(int staId, Area area, String staLabel, Date staLastCom,
			boolean staValid, Set<Sensor> sensors) {
		this.staId = staId;
		this.area = area;
		this.staLabel = staLabel;
		this.staLastCom = staLastCom;
		this.staValid = staValid;
		this.sensors = sensors;
	}

	public int getStaId() {
		return this.staId;
	}

	public void setStaId(int staId) {
		this.staId = staId;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getStaLabel() {
		return this.staLabel;
	}

	public void setStaLabel(String staLabel) {
		this.staLabel = staLabel;
	}

	public Date getStaLastCom() {
		return this.staLastCom;
	}

	public void setStaLastCom(Date staLastCom) {
		this.staLastCom = staLastCom;
	}

	public boolean isStaValid() {
		return this.staValid;
	}

	public void setStaValid(boolean staValid) {
		this.staValid = staValid;
	}

	public Set<Sensor> getSensors() {
		return this.sensors;
	}

	public void setSensors(Set<Sensor> sensors) {
		this.sensors = sensors;
	}

}
