package fr.utbm.core.entity;// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Temperature generated by hbm2java
 */
public class Temperature implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8698498739111142358L;
	private Integer tmpId;
	private Sensor sensor;
	private float tmpValue;
	private Date tmpDate;

	public Temperature() {
	}

	public Temperature(Sensor sensor, float tmpValue, Date tmpDate) {
		this.sensor = sensor;
		this.tmpValue = tmpValue;
		this.tmpDate = tmpDate;
	}

	public Integer getTmpId() {
		return this.tmpId;
	}

	public void setTmpId(Integer tmpId) {
		this.tmpId = tmpId;
	}

	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	public float getTmpValue() {
		return this.tmpValue;
	}

	public void setTmpValue(float tmpValue) {
		this.tmpValue = tmpValue;
	}

	public Date getTmpDate() {
		return this.tmpDate;
	}

	public void setTmpDate(Date tmpDate) {
		this.tmpDate = tmpDate;
	}

}
