package fr.utbm.core.entity;// default package
// Generated 31 oct. 2014 13:51:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Trigger generated by hbm2java
 */
public class Trigger implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -365383401489824783L;
	private int trgId;
	private Alert alert;
	private Sensor sensor;
	private float trgHigh;
	private float trgLow;
	private boolean trgEdge;
	private Set<Alerthis> alerthises = new HashSet<Alerthis>(0);

	public Trigger() {
	}

	public Trigger(int trgId, Alert alert, Sensor sensor, float trgHigh,
			float trgLow, boolean trgEdge) {
		this.trgId = trgId;
		this.alert = alert;
		this.sensor = sensor;
		this.trgHigh = trgHigh;
		this.trgLow = trgLow;
		this.trgEdge = trgEdge;
	}

	public Trigger(int trgId, Alert alert, Sensor sensor, float trgHigh,
			float trgLow, boolean trgEdge, Set<Alerthis> alerthises) {
		this.trgId = trgId;
		this.alert = alert;
		this.sensor = sensor;
		this.trgHigh = trgHigh;
		this.trgLow = trgLow;
		this.trgEdge = trgEdge;
		this.alerthises = alerthises;
	}

	public int getTrgId() {
		return this.trgId;
	}

	public void setTrgId(int trgId) {
		this.trgId = trgId;
	}

	public Alert getAlert() {
		return this.alert;
	}

	public void setAlert(Alert alert) {
		this.alert = alert;
	}

	public Sensor getSensor() {
		return this.sensor;
	}

	public void setSensor(Sensor sensor) {
		this.sensor = sensor;
	}

	public float getTrgHigh() {
		return this.trgHigh;
	}

	public void setTrgHigh(float trgHigh) {
		this.trgHigh = trgHigh;
	}

	public float getTrgLow() {
		return this.trgLow;
	}

	public void setTrgLow(float trgLow) {
		this.trgLow = trgLow;
	}

	public boolean isTrgEdge() {
		return this.trgEdge;
	}

	public void setTrgEdge(boolean trgEdge) {
		this.trgEdge = trgEdge;
	}

	public Set<Alerthis> getAlerthises() {
		return this.alerthises;
	}

	public void setAlerthises(Set<Alerthis> alerthises) {
		this.alerthises = alerthises;
	}

}
